### ISSUE TITLE
Direct link for image items

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#71]
We want to be a forum image host after all, right? 📦

**Comment by towerofnix** [comment]
IIRC I programmed there to be two URLs - `download` and `raw`. `download` ups the download count, `raw` is just to get the image. That might have changed though :P

**Comment by bates64** [comment]
Perhaps listen on what the browser wants from us? ie. when the browser wants an image from us (through `<img>`) we'll get a HTTP header - something like Requested Content Type? - that we can read and either redirect to `/raw` or just show the page like normal.

Because then people can just do `[image=http://opensprites.org/resources/someid]` and copy the URL, rather than having to copy some fancy `/raw` url :package:

**Comment by MegaApuTurkUltra** [comment]
Would the browser let us know with an accept header?

Just check if text/html isn't there :P

**Comment by bates64** [comment]
@MegaApuTurkUltra that's what I meant :tada:

**Comment by MegaApuTurkUltra** [comment]
Done
